### ISSUE TITLE
Problem running manpm with Node.js v5.2.0 under nvm

### ISSUE THREAD

**Issue by d2s** [bahmutov/manpm#21]
Problem running `manpm` with Node v5.2.0 version, when using [nvm](https://github.com/creationix/nvm) for managing Node.js versions.

Originally installed with:

```
$ npm install -g manpm
/home/d2s/.nvm/versions/node/v5.2.0/bin/manpm -> /home/d2s/.nvm/versions/node/v5.2.0/lib/node_modules/manpm/bin/manpm.js
/home/d2s/.nvm/versions/node/v5.2.0/lib
```

When running the software, `manpm` fails to find Node executable.

```
$ manpm bevacqua/es6 weaksets
/usr/bin/env: node --harmony: No such file or directory
```

Enviroment variables include path to Node.js binary folder.

```
$ /usr/bin/env | grep node
NVM_BIN=/home/d2s/.nvm/versions/node/v5.2.0/bin
NVM_PATH=/home/d2s/.nvm/versions/node/v5.2.0/lib/node
…
```

Directory has the `node` binary file: 

```
$ ll /home/d2s/.nvm/versions/node/v5.2.0/bin/node 
-rwxrwxr-x 1 d2s d2s 24M joulu  9 06:06 /home/d2s/.nvm/versions/node/v5.2.0/bin/node
```

Not really sure how this should be fixed, but the problem is probably caused by the line in [`manpm.js`](https://github.com/bahmutov/manpm/blob/master/bin/manpm.js#L1) file:

``` js
#!/usr/bin/env node --harmony
```

(Ubuntu, with `zsh` shell as the default console environment.)

**Comment by bahmutov** [comment]
hmm, seems different shells treat `--harmony` differently. I should probably not use this flag, instead only assume node > 4

**Comment by d2s** [comment]
Using [Oh My Zsh](http://ohmyz.sh/) -based `zsh` config, together with:

```
$ zsh --version                                  
zsh 5.0.2 (x86_64-pc-linux-gnu)
```
